/**
 * Seed script — populates DB with a workspace, feedback source, and sample
 * feedback items. Embeddings are generated by calling the live /api/ingest
 * endpoint so the OpenAI key from .env.local is used automatically.
 *
 * Usage (from WSL):
 *   node seed.js
 */

require('dotenv').config({ path: '.env.local' });
const { Client } = require('pg');

const DB_URL = process.env.DATABASE_URL || 'postgres://postgres:password@localhost:5432/neurodash';
const API_BASE = 'http://localhost:3000';

const SAMPLE_FEEDBACK = [
  { content: "The new checkout flow is really confusing. I can't find the promo code field and I ended up abandoning my cart.", sentiment: 'negative', category: 'checkout' },
  { content: "Checkout was buttery smooth this time! Applied my discount code in seconds. Great UX improvement.", sentiment: 'positive', category: 'checkout' },
  { content: "Why does the app crash every time I try to upload a profile photo on Android? This has been broken for weeks.", sentiment: 'negative', category: 'mobile-bug' },
  { content: "Love the new dark mode! My eyes thank you. Please add it to the mobile app too.", sentiment: 'positive', category: 'ui' },
  { content: "Your customer support response time is incredible. Got my issue resolved in under 10 minutes!", sentiment: 'positive', category: 'support' },
  { content: "Billing page shows incorrect charges. I was double-billed for last month and no one is responding to my tickets.", sentiment: 'negative', category: 'billing' },
  { content: "Search is painfully slow. Querying anything takes 5–10 seconds. Makes the product feel unusable.", sentiment: 'negative', category: 'performance' },
  { content: "The dashboard redesign is a massive improvement. The new charts are much easier to read at a glance.", sentiment: 'positive', category: 'dashboard' },
  { content: "Onboarding flow needs work. It's not clear what I need to set up first and I felt completely lost for the first hour.", sentiment: 'negative', category: 'onboarding' },
  { content: "The API documentation is excellent! Well structured, great code examples, and the sandbox works perfectly.", sentiment: 'positive', category: 'developer' },
  { content: "Push notifications are arriving 30–45 minutes late. By the time I see the alert, it's irrelevant.", sentiment: 'negative', category: 'notifications' },
  { content: "Integrating with Zapier was dead simple. Had my workflow running in under 5 minutes.", sentiment: 'positive', category: 'integrations' },
  { content: "Please add CSV export to the reports section. Having to copy data manually is a huge time sink.", sentiment: 'neutral', category: 'feature-request' },
  { content: "The mobile app drains my battery like crazy. After 2 hours of use, my phone is at 20% from 100%.", sentiment: 'negative', category: 'mobile-bug' },
  { content: "Two-factor authentication setup was flawless. Appreciate the extra security layer.", sentiment: 'positive', category: 'security' },
  { content: "The filters on the feedback list don't remember my selection when I navigate away. Super annoying.", sentiment: 'negative', category: 'ux' },
  { content: "Fantastic product overall. The semantic search feature alone saves our team hours every week.", sentiment: 'positive', category: 'general' },
  { content: "Payment gateway times out during peak hours. I've lost 3 sales this week because of this.", sentiment: 'negative', category: 'billing' },
  { content: "The new AI-generated summaries are surprisingly accurate. This feature is a game changer for our team.", sentiment: 'positive', category: 'ai-features' },
  { content: "Can't login with SSO on Safari. Works fine on Chrome but Safari just shows a blank white screen.", sentiment: 'negative', category: 'auth' },
];

async function createWorkspaceAndSource(client) {
  // Upsert workspace
  const wsRes = await client.query(
    `INSERT INTO workspaces (name) VALUES ($1)
     ON CONFLICT DO NOTHING
     RETURNING id`,
    ['Demo Workspace']
  );

  let workspaceId;
  if (wsRes.rows.length > 0) {
    workspaceId = wsRes.rows[0].id;
  } else {
    const existing = await client.query(`SELECT id FROM workspaces WHERE name = $1 LIMIT 1`, ['Demo Workspace']);
    workspaceId = existing.rows[0].id;
  }

  // Upsert feedback source
  const srcRes = await client.query(
    `INSERT INTO feedback_sources (workspace_id, source_type, name) VALUES ($1, $2, $3)
     ON CONFLICT DO NOTHING
     RETURNING id`,
    [workspaceId, 'custom', 'Sample Customer Feedback']
  );

  let sourceId;
  if (srcRes.rows.length > 0) {
    sourceId = srcRes.rows[0].id;
  } else {
    const existing = await client.query(`SELECT id FROM feedback_sources WHERE name = $1 LIMIT 1`, ['Sample Customer Feedback']);
    sourceId = existing.rows[0].id;
  }

  return sourceId;
}

async function ingestItem(sourceId, item, index) {
  const res = await fetch(`${API_BASE}/api/ingest`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      content: item.content,
      sourceId,
      metadata: { category: item.category, sentiment: item.sentiment },
    }),
  });

  const data = await res.json();
  if (!res.ok || data.error) {
    throw new Error(`Ingest failed for item ${index}: ${data.error}`);
  }
  return data;
}

async function main() {
  const client = new Client({ connectionString: DB_URL });
  await client.connect();
  console.log('Connected to database');

  // Check if data already exists
  const countRes = await client.query('SELECT COUNT(*) FROM feedback_items');
  const existingCount = parseInt(countRes.rows[0].count, 10);
  if (existingCount > 0) {
    console.log(`Database already has ${existingCount} feedback items. Skipping seed.`);
    console.log('To re-seed, run: DELETE FROM feedback_items; DELETE FROM feedback_sources; DELETE FROM workspaces;');
    await client.end();
    return;
  }

  const sourceId = await createWorkspaceAndSource(client);
  console.log(`Using feedback source ID: ${sourceId}`);
  await client.end();

  console.log(`\nIngesting ${SAMPLE_FEEDBACK.length} feedback items via /api/ingest...`);
  let success = 0;
  for (let i = 0; i < SAMPLE_FEEDBACK.length; i++) {
    const item = SAMPLE_FEEDBACK[i];
    try {
      await ingestItem(sourceId, item, i + 1);
      success++;
      process.stdout.write(`\r  [${success}/${SAMPLE_FEEDBACK.length}] ingested`);
    } catch (err) {
      console.error(`\n  ✗ ${err.message}`);
    }
    // Small delay to avoid rate limiting
    await new Promise(r => setTimeout(r, 300));
  }

  console.log(`\n\nDone! ${success}/${SAMPLE_FEEDBACK.length} items seeded successfully.`);
  console.log('You can now search at http://localhost:3000');
}

main().catch(err => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
